// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../examples/image/image.js', ['examples.image'], ['goog.events', 'orino.pano.view.JoystickControl', 'orino.pano.view.View', 'orino.pano.view.ZoomControl'], false);
goog.addDependency('../../../../src/orino/glu/glu.js', ['orino.glu'], ['goog.net.XhrIo'], false);
goog.addDependency('../../../../src/orino/pano/pano.js', ['orino.pano', 'orino.pano.Camera', 'orino.pano.Coordinates', 'orino.pano.Event', 'orino.pano.Projection'], ['goog.math.Vec2', 'goog.math.Vec3'], false);
goog.addDependency('../../../../src/orino/pano/view/control.js', ['orino.pano.view.Control'], [], false);
goog.addDependency('../../../../src/orino/pano/view/joystickcontrol.js', ['orino.pano.view.JoystickControl'], ['goog.events', 'goog.math.Vec2', 'orino.pano.view.Control'], false);
goog.addDependency('../../../../src/orino/pano/view/shaders/shaders.gen.js', ['orino.pano.view.shaders'], [], false);
goog.addDependency('../../../../src/orino/pano/view/shaders/zoomcontrol.js', ['orino.pano.view.ZoomControl'], ['goog.events.MouseWheelHandler', 'goog.userAgent', 'orino.pano.view.Control'], false);
goog.addDependency('../../../../src/orino/pano/view/view.js', ['orino.pano.view.View'], ['goog.Promise', 'goog.events.EventTarget', 'goog.math', 'goog.math.Size', 'goog.math.Vec3', 'goog.style', 'orino.anim', 'orino.anim.Conductor', 'orino.glu', 'orino.pano', 'orino.pano.view.shaders'], false);
goog.addDependency('../../../orino-anim/src/orino/anim/anim.js', ['orino.anim'], ['orino.anim.Conductor'], false);
goog.addDependency('../../../orino-anim/src/orino/anim/animation.js', ['orino.anim.Animation'], ['orino.anim.AnimationState'], false);
goog.addDependency('../../../orino-anim/src/orino/anim/animationstate.js', ['orino.anim.AnimationState'], [], false);
goog.addDependency('../../../orino-anim/src/orino/anim/conductor.js', ['orino.anim.Conductor'], ['orino.anim.Animation', 'orino.anim.Loop'], false);
goog.addDependency('../../../orino-anim/src/orino/anim/fps.js', ['orino.anim.fps', 'orino.anim.fps.Monitor', 'orino.anim.fps.View'], ['orino.anim.Animation'], false);
goog.addDependency('../../../orino-anim/src/orino/anim/loop.js', ['orino.anim.Loop'], [], false);
