// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../examples/image/image.js', ['examples.image'], [], false);
goog.addDependency('../../../../src/orino/glu/glu.js', ['orino.glu'], ['goog.net.XhrIo'], false);
goog.addDependency('../../../../src/orino/pano/pano.js', ['orino.pano', 'orino.pano.Camera', 'orino.pano.Coordinates', 'orino.pano.Event', 'orino.pano.Projection'], ['goog.math.Vec2', 'goog.math.Vec3'], false);
goog.addDependency('../../../../src/orino/pano/view/shaders/shaders.gen.js', ['orino.pano.view.shaders'], [], false);
goog.addDependency('../../../../src/orino/pano/view/view.js', ['orino.pano.view.View'], ['goog.Promise', 'goog.events.EventTarget', 'goog.math', 'goog.math.Size', 'goog.math.Vec3', 'orino.glu', 'orino.pano', 'orino.pano.view.shaders'], false);
